Localisation/Models/CultureSwitcherModel.cs
using System.Globalization;

namespace Localisation.Models
{
    public class CultureSwitcherModel
    {
        public CultureInfo CurrentUICulture { get; set; }
        public List<CultureInfo> SupportedCultures { get; set; }
    }
}

Localisation/Pages/Account/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Localisation.Pages.Account
{
    public class RegisterModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Localisation/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace Localisation.Pages
{
    [BindProperties]
    public class ContactModel : PageModel
    {
        [Display(Name = "Message"), Required(ErrorMessage = "Message Required")]
        public string Message { get; set; }
        [Display(Name = "First Name"), Required(ErrorMessage = "First Name Required")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name"), Required(ErrorMessage = "Last Name Required")]
        public string LastName { get; set; }
        [Display(Name = "Email"), Required(ErrorMessage = "Email Required"), DataType(DataType.EmailAddress)]
        public string Email { get; set; }
    }
}

Localisation/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Localisation.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Localisation/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Localisation.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty(SupportsGet = true, Name = "pageUrl")]
        public string PageUrl { get; set; }
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            string culture = (string) HttpContext.Request.RouteValues["culture"];
        }
    }
}

Localisation/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Localisation.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Localisation/Pages/Sample/Account/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Localisation.Pages.Sample.Account
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Localisation/Pages/Sample/Account/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Localisation.Pages.Sample.Account
{
    public class RegisterModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Localisation/ViewComponents/CultureSwitcherViewComponent.cs
using Localisation.Models;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Localisation.ViewComponents
{
    [ViewComponent]
    public class CultureSwitcherViewComponent : ViewComponent
    {
        private readonly IOptions<RequestLocalizationOptions> _localizationOptions;
        public CultureSwitcherViewComponent(IOptions<RequestLocalizationOptions> localizationOptions) =>
            _localizationOptions = localizationOptions;

        public IViewComponentResult Invoke()
        {
            var cultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
            var model = new CultureSwitcherModel
            {
                SupportedCultures = _localizationOptions.Value.SupportedUICultures.ToList(),
                CurrentUICulture = cultureFeature.RequestCulture.UICulture
            };
            return View(model);
        }
    }
}

Localisation/Pages/Account/Register.cshtml
@page
@inject IStringLocalizer<RegisterModel> localizer
@model Localisation.Pages.Account.RegisterModel
@{
}

<h1>@localizer["Test"]</h1>

Localisation/Pages/Contact.cshtml
@page
@inject CommonLocalizationService localizer
@model Localisation.Pages.ContactModel
@{
    ViewData["Title"] = localizer.Get("Contact Us");
}
 
<h1>@localizer.Get("Contact Us")</h1>
<form method="post">
    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input class="form-control" asp-for="FirstName">
        <span asp-validation-for="FirstName"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName"></label>
        <input class="form-control" asp-for="LastName">
        <span asp-validation-for="LastName"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input class="form-control" asp-for="Email">
        <span asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <label asp-for="Message"></label>
        <textarea class="form-control" asp-for="Message"></textarea>
        <span asp-validation-for="Message"></span>
    </div>
    <button class="btn btn-secondary">@localizer.Get("Submit")</button>
</form>
 
@section scripts{ 
    <partial name="_ValidationScriptsPartial"/>
}

Localisation/Pages/Index.cshtml
@page "{**pageUrl}"
@*@inject IStringLocalizer<IndexModel> localizer*@
@inject CommonLocalizationService localizer
@inject IHtmlLocalizer<IndexModel> htmlLocalizer
@model IndexModel
@{
    ViewData["Title"] = localizer.Get("Home");
    var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
    var requestCulture = requestCultureFeature.RequestCulture;
}
 <h6>@Model.PageUrl</h6>
<div class="text-center">
    <h1 class="display-4">@localizer.Get("Welcome")</h1>
    <p>@htmlLocalizer.GetHtml("Learn")</p>
 
    <table class="table culture-table">
        <tr>
            <td style="width:50%;">Culture</td>
            <td>@requestCulture.Culture.DisplayName {@requestCulture.Culture.Name}</td>
        </tr>
        <tr>
            <td>UI Culture</td>
            <td>@requestCulture.UICulture.Name</td>
        </tr>
        <tr>
            <td>UICulture Parent</td>
            <td>@requestCulture.UICulture.Parent</td>
        </tr>
        <tr>
            <td>Date</td>
            <td>@DateTime.Now.ToLongDateString()</td>
        </tr>
        <tr>
            <td>Currency</td>
            <td>
                @(12345.00.ToString("c"))
            </td>
        </tr>
        <tr>
            <td>Number</td>
            <td>
                @(123.45m.ToString("F2"))
            </td>
        </tr>
    </table>
</div>

Localisation/Pages/Sample/Account/Index.cshtml
@page
@model Localisation.Pages.Sample.Account.IndexModel
@{
}
<h1>Index</h1>

Localisation/Pages/Sample/Account/Register.cshtml
@page
@model Localisation.Pages.Sample.Account.RegisterModel
@{
}
<h1>Register</h1>

Localisation/Pages/Shared/Components/CultureSwitcher/default.cshtml
@model CultureSwitcherModel
<div>
    <form id="culture-switcher">
        <select name="culture" id="culture-options">
            @foreach (var culture in Model.SupportedCultures)
            {
                <option value="@culture.Name" selected="@(Model.CurrentUICulture.Name == culture.Name)">@culture.DisplayName</option>
            }
        </select>
    </form>
</div>
 
<script>
    //document.getElementById("culture-options").addEventListener("change", () => {
    //    document.getElementById("culture-switcher").submit();
    //});
    var segments = location.pathname.split('/');
    var el = document.getElementById("culture-options");
    el.addEventListener("change", () => {
        var culture = el.options[el.selectedIndex].value;
        if (segments.length >= 2) {
            segments[1] = culture;
            location.href = segments.join('/');
        } else {
            location.href = '/' + culture + location.pathname;
        }
    });
</script>

Localisation/Pages/Shared/_Layout.cshtml
@inject CommonLocalizationService localizer
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @localizer.Get("Localisation")</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Localisation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-route-pageUrl="" asp-page="/Index">@localizer.Get("Localisation")</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-route-pageUrl="" asp-page="/Index">@localizer.Get("Home")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">@localizer.Get("Privacy")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Contact">@localizer.Get("Contact")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-route-pageUrl="/chinh-sach-uu-dai-dau-tu/chinh-sach-uu-dai-dau-tu.htm" asp-page="/Index">Chính sách ưu đãi đầu tư</a>
                        </li>
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-route-pageUrl="/chinh-sach-uu-dai-dau-tu/chinh-sach-uu-dai-dau-tu.htm" asp-page="/Index">Chính sách ưu đãi đầu tư</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-route-pageUrl="/chinh-sach-uu-dai-dau-tu/chinh-sach-uu-dai-dau-tu.htm" asp-page="/Index">Chính sách ưu đãi đầu tư</a>
                        </li>*@
                    </ul>
                </div>
                @await Component.InvokeAsync("CultureSwitcher")
                @*<vc:culture-switcher/>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - @localizer.Get("Localisation") - <a asp-area="" asp-page="/Privacy">@localizer.Get("Privacy")</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>